### ISSUE TITLE
Only one graphics interface is detected in Optimus systems

### ISSUE THREAD

**Issue by gnutechie** [Utappia/sysglance#1]
When sysglance is running on an Optimus laptop (Intel [Integrated graphics] / Nvidia [Discreet Graphics]) only the one graphics interface is displayed as a result. 

The system only displays the results of lspci that have VGA in it's string.

This is only because the grep command only looks lines that match the string VGA where it should also include 3D and 2D.

The line to be complemented is line 67 in file sysglance.sh

and I think that it needs to be replaced by the following line:
lspci -k | grep -i 'vga\|3d\|2d'

**Comment by cerebrux** [comment]
Thanks for the report! I will do some testing and will replace it with your proposal. If you do test it in any distribution, please comment below.

**Comment by cerebrux** [comment]
Can you please test the latest version ? And report back with the output, just to check if all your VGA card are printed. Also check the new features :)

**Comment by gnutechie** [comment]
Your patch works out ok. It shows both of my graphics cards.
![Screenshot at 2019-11-05 13-36-46](https://user-images.githubusercontent.com/8708330/68244285-bd425700-ffd1-11e9-8f1f-6a8abf93128a.png)
